@startuml

class RadioBottomBarPlayer {}

interface IBaseProps {}
interface ICommonProps {}

RadioBottomBarPlayer --o IBaseProps
IBaseProps ..|> ICommonProps

RadioBottomBarPlayer --> useUILogic

class client {}

client --> RadioBottomBarPlayer
@enduml