name: CD main publish

on:
  push: 
    branches: 
      - main
      
concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  
jobs:
 
  publish:
    runs-on: ubuntu-latest

    outputs:
      latestVersion: echo "${{fromJson(steps.changesets.outputs.publishedPackages)[0].version}}"

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: yarn
      
      - name: Make Versioning and Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    needs: publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ needs.publish.outputs.latestVersion }}


      




