name: CI

on:
  pull_request:
    types: [opened, review_requested, edited, synchronize]
    branches: 
      - "**"

jobs:
  development-ci:
    name: development-ci
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      
      - name: branch name
        id: get-branch-name
        run: echo  "branch-prefix=$(echo ${GITHUB_HEAD_REF} | sed 's/\(^\w\+\)\/.*/\1/')" >> $GITHUB_OUTPUT

      - name: get prefix
        run: echo ${{steps.get-branch-name.outputs.branch-prefix}}

      - name: Version Bump
        run: |
          if [ "${{ steps.get-branch-name.outputs.branch-prefix }}" == "feature" ]
          then
            npm version minor --force --no-git-tag-version
            echo "Bumping version: minor"
          elif  [ "${{ steps.get-branch-name.outputs.branch-prefix }}" == "fix" ] 
          then
            npm version patch --force --no-git-tag-version
            echo "Bumping version: patch"
          elif  [ "${{ steps.get-branch-name.outputs.branch-prefix }}" == "change" ] 
          then
            npm version major --force --no-git-tag-version
            echo "Bumping version: major"
          else
            echo "No version bump needed for this branch as its prefix is ${{ steps.get-branch-name.outputs.branch-prefix }}"
          fi

      - name: install dependencies
        run: yarn

      - name: Commit version change
        run: |
          git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
          git config --local user.name "$(git log -n 1 --pretty=format:%an)"
          git checkout ${GITHUB_HEAD_REF}
          git add package.json
          git commit -m "Bump version"
          git push

      - name: linting
        run: yarn lint

      - name: build
        run: yarn build
