name: CI

on:
  pull_request:
    types: [opened, review_requested, edited, synchronize]
    branches: 
      - "**"

jobs:
  development-ci:
    name: development-ci
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      
      - name: branch name
        id: get-branch-name
        run: echo  "branch-prefix=$(echo ${GITHUB_HEAD_REF} | sed 's/\(^\w\+\)\/.*/\1/')" >> $GITHUB_OUTPUT

      - name: get prefix
        run: echo ${{steps.get-branch-name.outputs.branch-prefix}}

      - name: Version Bump
        run: |
          if [ "${{ steps.get-branch-name.outputs.branch-prefix }}" -eq "feature" ] then
            npm version minor --force --no-git-tag-version
          elif  [ "${{ steps.get-branch-name.outputs.branch-prefix }}" -eq "fix" ] then
            npm version patch --force --no-git-tag-version
          elif  [ "${{ steps.get-branch-name.outputs.branch-prefix }}" -eq "change" ] then
            npm version major --force --no-git-tag-version
          else
            echo "No version bump needed for this branch as its prefix is ${{ steps.get-branch-name.outputs.branch-prefix }}"
          fi

      - name: install dependencies
        run: yarn

      - name: linting
        run: yarn lint

      - name: build
        run: yarn build
