name: Staging

on:
  pull_request: 
    types: 
      - closed
    branches: 
      - develop

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
  
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      
      - name: branch name
        id: get-branch-name
        run: echo  "branch-prefix=$(echo ${GITHUB_HEAD_REF} | sed 's/\(^\w\+\)\/.*/\1/')" >> $GITHUB_OUTPUT

      - name: get prefix
        run: echo ${{steps.get-branch-name.outputs.branch-prefix}}

      - name: Version Bump
        id: bump
        run: |
          if [ "${{ steps.get-branch-name.outputs.branch-prefix }}" == "feature" ]
          then
            npm version minor --force --no-git-tag-version
            echo "Bumping version: minor"
            echo "bumped-version=minor" >> $GITHUB_OUTPUT
          elif  [ "${{ steps.get-branch-name.outputs.branch-prefix }}" == "fix" ] 
          then
            npm version patch --force --no-git-tag-version
            echo "Bumping version: patch"
            echo "bumped-version=patch" >> $GITHUB_OUTPUT
          elif  [ "${{ steps.get-branch-name.outputs.branch-prefix }}" == "change" ] 
          then
            npm version major --force --no-git-tag-version
            echo "Bumping version: major"
            echo "bumped-version=major" >> $GITHUB_OUTPUT
          else
            echo "No version bump needed for this branch as its prefix is ${{ steps.get-branch-name.outputs.branch-prefix }}"
            echo "bumped-version=null" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit version change
        if: ${{steps.bump.outputs.bumped-version != null }}
        run: |
          git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
          git config --local user.name "$(git log -n 1 --pretty=format:%an)"
          git add package.json
          git commit -m "Bump version ${{ steps.bump.outputs.bumped-version }}"

      - name: Push changes
        if: steps.bump.outputs.bumped-version != null 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  storybook-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: install dependencies
        run: yarn
      
      - name: Pre deploy
        run: yarn predeploy
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
      